### ISSUE TITLE
The example is not working

### ISSUE THREAD

**Issue by pablojimenezmateo** [TinyCircuits/TinyCircuits-TinyShield-RTC-ASD2831#1]
When compiling the project (and fixing the dependencies), it gives the following error:

> In file included from C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:22:0:
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:224:6: error: #error "No SLEEP mode defined for this device."
>      #error "No SLEEP mode defined for this device."
>       ^~~~~
> exit status 1
> Error compiling for board TinyScreen+.

And even when deleting that directive (by eliminating lines 222 to 224 from sleep.h), there is another error:

> In file included from C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:19:0:
> C:\Users\Gef\Documents\Arduino\libraries\DSRTCLib/DSRTCLib.h:90:23: error: conflicting declaration 'typedef long unsigned int time_t'
>  typedef unsigned long time_t;
>                        ^~~~~~
> In file included from c:\users\gef\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\sys\select.h:26:0,
>                  from c:\users\gef\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\sys\types.h:68,
>                  from c:\users\gef\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\stdio.h:61,
>                  from C:\Users\Gef\AppData\Local\Arduino15\packages\TinyCircuits\hardware\samd\1.1.0\cores\arduino/Print.h:23,
>                  from C:\Users\Gef\AppData\Local\Arduino15\packages\TinyCircuits\hardware\samd\1.1.0\cores\arduino/Stream.h:26,
>                  from C:\Users\Gef\AppData\Local\Arduino15\packages\TinyCircuits\hardware\samd\1.1.0\cores\arduino/HardwareSerial.h:24,
>                  from C:\Users\Gef\AppData\Local\Arduino15\packages\TinyCircuits\hardware\samd\1.1.0\cores\arduino/Arduino.h:78,
>                  from sketch\RTC_TinyShield_example.ino.cpp:1:
> c:\users\gef\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\sys\_timeval.h:40:18: note: previous declaration as 'typedef __int_least64_t time_t'
>  typedef _TIME_T_ time_t;
>                   ^~~~~~
> In file included from C:\Users\Gef\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/samd21/include/samd21.h:69:0,
>                  from C:\Users\Gef\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/samd.h:105,
>                  from C:\Users\Gef\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/sam.h:540,
>                  from C:\Users\Gef\AppData\Local\Arduino15\packages\TinyCircuits\hardware\samd\1.1.0\cores\arduino/Arduino.h:48,
>                  from sketch\RTC_TinyShield_example.ino.cpp:1:
> C:\Users\Gef\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/samd21/include/samd21g18a.h:487:38: error: expected ')' before '*' token
>  #define RTC               ((Rtc      *)0x40001400UL) /**< \brief (RTC) APB Base Address */
>                                       ^
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:39:8: note: in expansion of macro 'RTC'
>  DS1339 RTC = DS1339(INT_PIN, int_number);
>         ^~~
> C:\Users\Gef\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/samd21/include/samd21g18a.h:487:38: error: expected ')' before '*' token
>  #define RTC               ((Rtc      *)0x40001400UL) /**< \brief (RTC) APB Base Address */
>                                       ^
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:39:8: note: in expansion of macro 'RTC'
>  DS1339 RTC = DS1339(INT_PIN, int_number);
>         ^~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'void setup()':
> RTC_TinyShield_example:52:18: error: 'SLEEP_MODE_PWR_DOWN' was not declared in this scope
>    set_sleep_mode(SLEEP_MODE_PWR_DOWN);
>                   ^~~~~~~~~~~~~~~~~~~
> RTC_TinyShield_example:52:3: error: 'set_sleep_mode' was not declared in this scope
>    set_sleep_mode(SLEEP_MODE_PWR_DOWN);
>    ^~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:52:3: note: suggested alternative: 'sleep_mode'
>    set_sleep_mode(SLEEP_MODE_PWR_DOWN);
>    ^~~~~~~~~~~~~~
>    sleep_mode
> In file included from C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:22:0:
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:164:33: error: 'MCUCR' was not declared in this scope
>      #define _SLEEP_CONTROL_REG  MCUCR
>                                  ^
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:248:3: note: in expansion of macro '_SLEEP_CONTROL_REG'
>    _SLEEP_CONTROL_REG |= (uint8_t)_SLEEP_ENABLE_MASK;   \
>    ^~~~~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:53:3: note: in expansion of macro 'sleep_enable'
>    sleep_enable();
>    ^~~~~~~~~~~~
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:165:37: error: 'SE' was not declared in this scope
>      #define _SLEEP_ENABLE_MASK  _BV(SE)
>                                      ^
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:248:34: note: in expansion of macro '_SLEEP_ENABLE_MASK'
>    _SLEEP_CONTROL_REG |= (uint8_t)_SLEEP_ENABLE_MASK;   \
>                                   ^~~~~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:53:3: note: in expansion of macro 'sleep_enable'
>    sleep_enable();
>    ^~~~~~~~~~~~
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:165:37: note: suggested alternative: 'SS'
>      #define _SLEEP_ENABLE_MASK  _BV(SE)
>                                      ^
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:248:34: note: in expansion of macro '_SLEEP_ENABLE_MASK'
>    _SLEEP_CONTROL_REG |= (uint8_t)_SLEEP_ENABLE_MASK;   \
>                                   ^~~~~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:53:3: note: in expansion of macro 'sleep_enable'
>    sleep_enable();
>    ^~~~~~~~~~~~
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:165:33: error: '_BV' was not declared in this scope
>      #define _SLEEP_ENABLE_MASK  _BV(SE)
>                                  ^
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:248:34: note: in expansion of macro '_SLEEP_ENABLE_MASK'
>    _SLEEP_CONTROL_REG |= (uint8_t)_SLEEP_ENABLE_MASK;   \
>                                   ^~~~~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:53:3: note: in expansion of macro 'sleep_enable'
>    sleep_enable();
>    ^~~~~~~~~~~~
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:165:33: note: suggested alternative: '_B'
>      #define _SLEEP_ENABLE_MASK  _BV(SE)
>                                  ^
> C:\Users\Gef\Documents\Arduino\libraries\avr/sleep.h:248:34: note: in expansion of macro '_SLEEP_ENABLE_MASK'
>    _SLEEP_CONTROL_REG |= (uint8_t)_SLEEP_ENABLE_MASK;   \
>                                   ^~~~~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino:53:3: note: in expansion of macro 'sleep_enable'
>    sleep_enable();
>    ^~~~~~~~~~~~
> RTC_TinyShield_example:59:7: error: request for member 'start' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.start(); // ensure RTC oscillator is running, if not already
>        ^~~~~
> RTC_TinyShield_example:61:11: error: request for member 'time_is_set' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    if(!RTC.time_is_set()) { // set a time, if none set already...
>            ^~~~~~~~~~~
> RTC_TinyShield_example:67:11: error: request for member 'time_is_set' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    if(!RTC.time_is_set()) {
>            ^~~~~~~~~~~
> RTC_TinyShield_example:71:7: error: request for member 'enable_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.enable_interrupt();
>        ^~~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'int set_alarm()':
> RTC_TinyShield_example:110:7: error: request for member 'readAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.readAlarm();
>        ^~~~~~~~~
> RTC_TinyShield_example:111:24: error: request for member 'getHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    Serial.print(int(RTC.getHours()));
>                         ^~~~~~~~
> RTC_TinyShield_example:113:24: error: request for member 'getMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    Serial.print(int(RTC.getMinutes()));
>                         ^~~~~~~~~~
> RTC_TinyShield_example:115:26: error: request for member 'getSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    Serial.println(int(RTC.getSeconds()));
>                           ^~~~~~~~~~
> RTC_TinyShield_example:141:13: error: request for member 'setHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.setHours(hour);
>              ^~~~~~~~
> RTC_TinyShield_example:142:13: error: request for member 'setMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.setMinutes(minute);
>              ^~~~~~~~~~
> RTC_TinyShield_example:143:13: error: request for member 'setSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.setSeconds(second);
>              ^~~~~~~~~~
> RTC_TinyShield_example:144:13: error: request for member 'setAlarmRepeat' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.setAlarmRepeat(EVERY_WEEK);
>              ^~~~~~~~~~~~~~
> RTC_TinyShield_example:145:13: error: request for member 'writeAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.writeAlarm();
>              ^~~~~~~~~~
> RTC_TinyShield_example:158:11: error: request for member 'clear_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>        RTC.clear_interrupt();
>            ^~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'void set_time()':
> RTC_TinyShield_example:290:9: error: request for member 'setSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setSeconds(second);
>          ^~~~~~~~~~
> RTC_TinyShield_example:291:9: error: request for member 'setMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setMinutes(minute);
>          ^~~~~~~~~~
> RTC_TinyShield_example:292:9: error: request for member 'setHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setHours(hour);
>          ^~~~~~~~
> RTC_TinyShield_example:293:9: error: request for member 'setDays' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setDays(day);
>          ^~~~~~~
> RTC_TinyShield_example:294:9: error: request for member 'setMonths' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setMonths(month);
>          ^~~~~~~~~
> RTC_TinyShield_example:295:9: error: request for member 'setYears' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setYears(year);
>          ^~~~~~~~
> RTC_TinyShield_example:296:9: error: request for member 'writeTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.writeTime();
>          ^~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'void read_time()':
> RTC_TinyShield_example:304:7: error: request for member 'readTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.readTime(); // update RTC library's buffers from chip
>        ^~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'void test_basic()':
> RTC_TinyShield_example:313:7: error: request for member 'readTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.readTime(); // update RTC library's buffers from chip
>        ^~~~~~~~
> RTC_TinyShield_example:317:9: error: request for member 'setSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setSeconds(56);
>          ^~~~~~~~~~
> RTC_TinyShield_example:318:9: error: request for member 'setMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setMinutes(34);
>          ^~~~~~~~~~
> RTC_TinyShield_example:319:9: error: request for member 'setHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setHours(12);
>          ^~~~~~~~
> RTC_TinyShield_example:320:9: error: request for member 'setDays' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setDays(31);
>          ^~~~~~~
> RTC_TinyShield_example:321:9: error: request for member 'setMonths' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setMonths(1);
>          ^~~~~~~~~
> RTC_TinyShield_example:322:9: error: request for member 'setYears' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setYears(2007); // 2-digit or 4-digit years are supported
>          ^~~~~~~~
> RTC_TinyShield_example:323:9: error: request for member 'writeTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.writeTime();
>          ^~~~~~~~~
> RTC_TinyShield_example:325:9: error: request for member 'readTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.readTime();
>          ^~~~~~~~
> RTC_TinyShield_example:332:9: error: request for member 'writeTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.writeTime(2971468800);
>          ^~~~~~~~~
> RTC_TinyShield_example:334:9: error: request for member 'readTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.readTime();
>          ^~~~~~~~
> RTC_TinyShield_example:340:9: error: request for member 'setSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setSeconds(0);
>          ^~~~~~~~~~
> RTC_TinyShield_example:341:9: error: request for member 'setMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setMinutes(0);
>          ^~~~~~~~~~
> RTC_TinyShield_example:342:9: error: request for member 'setHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setHours(8);
>          ^~~~~~~~
> RTC_TinyShield_example:343:9: error: request for member 'setDays' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setDays(15);
>          ^~~~~~~
> RTC_TinyShield_example:344:9: error: request for member 'setAlarmRepeat' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setAlarmRepeat(EVERY_MONTH); // There is no DS1339 setting for 'alarm once' - user must shut off the alarm after it goes off.
>          ^~~~~~~~~~~~~~
> RTC_TinyShield_example:345:9: error: request for member 'writeAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.writeAlarm();
>          ^~~~~~~~~~
> RTC_TinyShield_example:347:9: error: request for member 'readAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.readAlarm();
>          ^~~~~~~~~
> RTC_TinyShield_example:352:9: error: request for member 'setSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setSeconds(5);
>          ^~~~~~~~~~
> RTC_TinyShield_example:353:9: error: request for member 'setMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setMinutes(31);
>          ^~~~~~~~~~
> RTC_TinyShield_example:354:9: error: request for member 'setHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setHours(14);
>          ^~~~~~~~
> RTC_TinyShield_example:355:9: error: request for member 'setDayOfWeek' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setDayOfWeek(3);
>          ^~~~~~~~~~~~
> RTC_TinyShield_example:356:9: error: request for member 'setAlarmRepeat' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setAlarmRepeat(EVERY_WEEK); // to alarm on matching day-of-week instead of date
>          ^~~~~~~~~~~~~~
> RTC_TinyShield_example:357:9: error: request for member 'writeAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.writeAlarm();
>          ^~~~~~~~~~
> RTC_TinyShield_example:359:9: error: request for member 'readAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.readAlarm();
>          ^~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'void test_interrupts()':
> RTC_TinyShield_example:380:7: error: request for member 'enable_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.enable_interrupt();
>        ^~~~~~~~~~~~~~~~
> RTC_TinyShield_example:381:7: error: request for member 'setAlarmRepeat' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.setAlarmRepeat(EVERY_SECOND); // if alarming every second, time registers larger than 1 second (hour, etc.) are don't-care
>        ^~~~~~~~~~~~~~
> RTC_TinyShield_example:382:7: error: request for member 'writeAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.writeAlarm();
>        ^~~~~~~~~~
> RTC_TinyShield_example:391:9: error: request for member 'clear_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.clear_interrupt();
>          ^~~~~~~~~~~~~~~
> RTC_TinyShield_example:398:9: error: request for member 'clear_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.clear_interrupt();
>          ^~~~~~~~~~~~~~~
> RTC_TinyShield_example:401:7: error: request for member 'disable_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.disable_interrupt(); // ensure we stop receiving interrupts
>        ^~~~~~~~~~~~~~~~~
> RTC_TinyShield_example:409:7: error: request for member 'snooze' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    RTC.snooze(10);
>        ^~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'void test_epoch_seconds()':
> RTC_TinyShield_example:444:9: error: request for member 'writeTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.writeTime(old_epoch_seconds); // reset time to epoch
>          ^~~~~~~~~
> RTC_TinyShield_example:445:9: error: request for member 'setAlarmRepeat' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.setAlarmRepeat(EVERY_DAY);
>          ^~~~~~~~~~~~~~
> RTC_TinyShield_example:446:9: error: request for member 'writeAlarm' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.writeAlarm(old_epoch_seconds); // ensure alarm starts at a valid value too
>          ^~~~~~~~~~
> RTC_TinyShield_example:448:9: error: request for member 'enable_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.enable_interrupt(); // make RTC generate a pulse every time one 'day' passes
>          ^~~~~~~~~~~~~~~~
> RTC_TinyShield_example:454:13: error: request for member 'readTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.readTime();  // restore known-good copy of date/time from chip to library's buffer
>              ^~~~~~~~
> RTC_TinyShield_example:455:13: error: request for member 'setHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.setHours(23);
>              ^~~~~~~~
> RTC_TinyShield_example:456:13: error: request for member 'setMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.setMinutes(59);
>              ^~~~~~~~~~
> RTC_TinyShield_example:457:13: error: request for member 'setSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.setSeconds(59);
>              ^~~~~~~~~~
> RTC_TinyShield_example:458:13: error: request for member 'writeTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.writeTime(); // note: writing a new time resets the RTC's oscillator count ("milliseconds") to 0, so we have a full second until the next interrupt happens.
>              ^~~~~~~~~
> RTC_TinyShield_example:462:13: error: request for member 'readTime' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.readTime();
>              ^~~~~~~~
> RTC_TinyShield_example:465:22: error: request for member 'getSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          second = RTC.getSeconds();
>                       ^~~~~~~~~~
> RTC_TinyShield_example:466:22: error: request for member 'getMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          minute = RTC.getMinutes();
>                       ^~~~~~~~~~
> RTC_TinyShield_example:467:20: error: request for member 'getHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          hour = RTC.getHours();
>                     ^~~~~~~~
> RTC_TinyShield_example:468:19: error: request for member 'getDays' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          day = RTC.getDays();
>                    ^~~~~~~
> RTC_TinyShield_example:469:21: error: request for member 'getMonths' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          month = RTC.getMonths();
>                      ^~~~~~~~~
> RTC_TinyShield_example:470:20: error: request for member 'getYears' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          year = RTC.getYears();
>                     ^~~~~~~~
> RTC_TinyShield_example:475:33: error: request for member 'date_to_epoch_seconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          new_epoch_seconds = RTC.date_to_epoch_seconds();
>                                  ^~~~~~~~~~~~~~~~~~~~~
> RTC_TinyShield_example:483:13: error: request for member 'epoch_seconds_to_date' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          RTC.epoch_seconds_to_date(new_epoch_seconds);
>              ^~~~~~~~~~~~~~~~~~~~~
> RTC_TinyShield_example:486:27: error: request for member 'getSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          if( second == RTC.getSeconds() && minute == RTC.getMinutes() && hour == RTC.getHours() && day == RTC.getDays() && month == RTC.getMonths() && year == RTC.getYears() )
>                            ^~~~~~~~~~
> RTC_TinyShield_example:486:57: error: request for member 'getMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          if( second == RTC.getSeconds() && minute == RTC.getMinutes() && hour == RTC.getHours() && day == RTC.getDays() && month == RTC.getMonths() && year == RTC.getYears() )
>                                                          ^~~~~~~~~~
> RTC_TinyShield_example:486:85: error: request for member 'getHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          if( second == RTC.getSeconds() && minute == RTC.getMinutes() && hour == RTC.getHours() && day == RTC.getDays() && month == RTC.getMonths() && year == RTC.getYears() )
>                                                                                      ^~~~~~~~
> RTC_TinyShield_example:486:110: error: request for member 'getDays' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          if( second == RTC.getSeconds() && minute == RTC.getMinutes() && hour == RTC.getHours() && day == RTC.getDays() && month == RTC.getMonths() && year == RTC.getYears() )
>                                                                                                               ^~~~~~~
> RTC_TinyShield_example:486:136: error: request for member 'getMonths' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          if( second == RTC.getSeconds() && minute == RTC.getMinutes() && hour == RTC.getHours() && day == RTC.getDays() && month == RTC.getMonths() && year == RTC.getYears() )
>                                                                                                                                         ^~~~~~~~~
> RTC_TinyShield_example:486:163: error: request for member 'getYears' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>          if( second == RTC.getSeconds() && minute == RTC.getMinutes() && hour == RTC.getHours() && day == RTC.getDays() && month == RTC.getMonths() && year == RTC.getYears() )
>                                                                                                                                                                    ^~~~~~~~
> RTC_TinyShield_example:497:9: error: request for member 'disable_interrupt' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      RTC.disable_interrupt();
>          ^~~~~~~~~~~~~~~~~
> C:\Users\Gef\Documents\GitHub\Take\Tests\RTC_TinyShield_example\RTC_TinyShield_example.ino: In function 'void printTime(byte)':
> RTC_TinyShield_example:508:26: error: request for member 'getMonths' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      Serial.print(int(RTC.getMonths()));
>                           ^~~~~~~~~
> RTC_TinyShield_example:510:26: error: request for member 'getDays' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      Serial.print(int(RTC.getDays()));
>                           ^~~~~~~
> RTC_TinyShield_example:512:22: error: request for member 'getYears' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>      Serial.print(RTC.getYears());
>                       ^~~~~~~~
> RTC_TinyShield_example:518:28: error: request for member 'getDayOfWeek' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>        Serial.print(int(RTC.getDayOfWeek()));
>                             ^~~~~~~~~~~~
> RTC_TinyShield_example:523:28: error: request for member 'getDays' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>        Serial.print(int(RTC.getDays()));
>                             ^~~~~~~
> RTC_TinyShield_example:529:24: error: request for member 'getHours' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    Serial.print(int(RTC.getHours()));
>                         ^~~~~~~~
> RTC_TinyShield_example:531:24: error: request for member 'getMinutes' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    Serial.print(int(RTC.getMinutes()));
>                         ^~~~~~~~~~
> RTC_TinyShield_example:533:24: error: request for member 'getSeconds' in '(Rtc*)1073746944', which is of pointer type 'Rtc*' (maybe you meant to use '->' ?)
>    Serial.print(int(RTC.getSeconds()));
>                         ^~~~~~~~~~
> exit status 1
> 'SLEEP_MODE_PWR_DOWN' was not declared in this scope

*OS:* Windows 10
*Arduino IDE:* 1.8.13

Also I can compile other code for the TinyScreen+ without issues. Let me know if you need more traces.

Thanks!

**Comment by TinyCircuits** [comment]
This example is meant for the [RTC TinyShield](https://tinycircuits.com/collections/sensors/products/real-time-clock-tinyshield). 

If you want to use the RTC on the TinyScreen+, you can refer to this tutorial: https://tinycircuits.com/blogs/learn/tinyscreen-external-interrupt-sleep-mode
